### Get Juice Recipes
GET http://localhost:8080/api/v1/juice-recipes

### Get Juice Recipes
GET http://localhost:8080/api/v1/juice-recipes/1

###
POST http://localhost:8080/api/v1/juice-recipes
Content-Type: application/json

{
"name":"Celery Juice",
"ingredient":"Celery,Green apple,Lemon,Ginger"
}

###
POST http://localhost:8080/api/v1/juice-recipes
Content-Type: application/json

{
"name":"Mulled Apple Juice",
"ingredient":"Apple juice,Orange peel,Cinnamon stick,Cloves,Sugar"
}